version: '3.1'
services:
    jenkins:
        container_name: jenkins
        ports:
            - '8080:8080'

        image: 13.235.79.78:8080/jenkins
    jenkins-slave:
        container_name: jenkins-slave
        restart: always
        environment:
            - 'JENKINS_URL=http://13.235.79.78:8080'
        image: 13.235.79.78:8080/jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /home/jenkins:/home/jenkins

        depends_on:
            - jenkins
